# Generated by Django 6.0.3 on 2026-03-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
